### ISSUE TITLE
Removing a note on key lane during keysound playback causes a crash.

### ISSUE THREAD

**Issue by TomoAlien** [excln/BmsONE#9] opened 2017-04-27 18:34 UTC
BmsONE 0.1.5 crashes when you remove a keysound while it's playing back and it's on the key lane.
This doesn't happen to keysounds located on a BGM lane.

The easiest way to reproduce it is to create/edit a note on a key lane (which will play it back), then remove it during the playback. This consistently causes a crash.

**Comment by DolphinDTM** [comment] 2017-04-27 18:37
I think this error is referenced here: https://github.com/excln/BmsONE/issues/4

**Comment by excln** [comment] 2017-05-09 17:09
I couldn't reproduce it on neither Windows nor Mac. Does it happen with any bmson? Is Master Cache enabled?

**Comment by TomoAlien** [comment] 2017-05-09 22:48
Yes, it happens on any bmson, and with master cache both disabled and enabled.

Here's a video of the bug in action:
https://www.youtube.com/watch?v=zu_HcGOxiRw

**Comment by excln** [comment] 2017-05-10 12:47
OK, I finally reproduced it. It happens only on right clicking (not pressing Delete key) on the note in Write Mode regardless of the playback. It's been already fixed in the master branch. Please check the next release.

**Comment by excln** [comment] 2017-09-24 10:38
Fixed at [beta 0.2.1](https://github.com/excln/BmsONE/releases/tag/beta_021).

**Closed as completed by excln** 2017-09-24 10:38 UTC
Labels: bug
